# Generated by Django 5.2.4 on 2025-08-01 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Learning_App', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GeeksModel',
            new_name='Model',
        ),
    ]
